# Phase 1 Objective

*The purpose of this notebook is only to load the raw dataset into memory and perform an initial inspection without making any modifications*

*This notebook establishes a reproducible starting point for the entire project.*

**Inputs** <br>
Raw CSV dataset<br>
Python environment<br>
Required libraries<br>

**Outputs**<br>
raw_df<br>
Initial understanding of the dataset structure<br>
Metadata about rows, columns, and data types<br>


**Expected Deliverables**<br><br>

By the end of this notebook we should know : <br>
dataset size<br>
column names<br>
variable types<br>
memory usage<br>
first few records<br>
last few records<br>

<h3>Importing the neccesary libraries and dataset</h3>

In [83]:
import pandas as pd
import numpy as np

raw_df = pd.read_csv("dataset\\main_dataset.csv")

In [84]:
rows, columns = raw_df.shape


print(f"Number of Rows    : {rows}")
print(f"Number of Columns : {columns}")

Number of Rows    : 15972
Number of Columns : 24

In [85]:
print("First Five Records")
display(raw_df.head())

print("\nLast Five Records")
display(raw_df.tail())

First Five Records

,Timestamp,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,TODO_COMPLETED,FLOW,DAILY_STEPS,LIVE_VISION,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,AGE,GENDER,WORK_LIFE_BALANCE_SCORE
0,07-07-2015,3,2,2,5,0,5,2,0,1,6,4,5,0,7,5,5,1,4,0,5,36 to 50,Female,609.5
1,07-07-2015,2,3,4,3,8,10,5,2,2,5,2,5,5,8,2,2,2,3,2,6,36 to 50,Female,655.6
2,07-07-2015,2,3,3,4,4,10,3,2,2,2,2,4,5,8,10,2,2,4,8,3,36 to 50,Female,631.6
3,07-07-2015,3,3,10,3,10,7,2,5,2,3,5,5,0,5,7,5,1,5,2,0,51 or more,Female,622.7
4,07-07-2015,5,1,3,3,10,4,2,4,2,5,0,5,0,7,0,0,2,8,1,5,51 or more,Female,663.9

Last Five Records

,Timestamp,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,TODO_COMPLETED,FLOW,DAILY_STEPS,LIVE_VISION,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,AGE,GENDER,WORK_LIFE_BALANCE_SCORE
15967,3/14/21 5:42,3,3,0,4,0,10,0,4,2,8,2,10,7,7,0,1,1,5,2,5,51 or more,Female,644.5
15968,3/14/21 6:30,3,3,6,8,7,4,6,3,1,7,5,6,5,6,0,0,2,10,5,8,21 to 35,Female,714.9
15969,3/14/21 8:35,4,3,0,10,10,8,6,5,1,7,3,5,2,7,0,1,2,10,1,10,21 to 35,Male,716.6
15970,3/14/21 8:43,1,1,10,8,2,7,3,2,1,6,10,1,5,8,7,2,2,1,6,8,21 to 35,Female,682.0
15971,3/14/21 9:03,5,4,0,2,10,10,5,1,2,7,4,1,5,8,5,2,2,1,8,4,21 to 35,Female,651.4

In [86]:
raw_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15972 entries, 0 to 15971
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Timestamp                15972 non-null  str
 1   FRUITS_VEGGIES           15972 non-null  int64
 2   DAILY_STRESS             15972 non-null  str
 3   PLACES_VISITED           15972 non-null  int64
 4   CORE_CIRCLE              15972 non-null  int64
 5   SUPPORTING_OTHERS        15972 non-null  int64
 6   SOCIAL_NETWORK           15972 non-null  int64
 7   ACHIEVEMENT              15972 non-null  int64
 8   DONATION                 15972 non-null  int64
 9   BMI_RANGE                15972 non-null  int64
 10  TODO_COMPLETED           15972 non-null  int64
 11  FLOW                     15972 non-null  int64
 12  DAILY_STEPS              15972 non-null  int64
 13  LIVE_VISION              15972 non-null  int64
 14  SLEEP_HOURS              15972 non-null  int64
 15  LOST_VACATION            15972 non-null  int64
 16  DAILY_SHOUTING           15972 non-null  int64
 17  SUFFICIENT_INCOME        15972 non-null  int64
 18  PERSONAL_AWARDS          15972 non-null  int64
 19  TIME_FOR_PASSION         15972 non-null  int64
 20  WEEKLY_MEDITATION        15972 non-null  int64
 21  AGE                      15972 non-null  str
 22  GENDER                   15972 non-null  str
 23  WORK_LIFE_BALANCE_SCORE  15972 non-null  float64
dtypes: float64(1), int64(19), str(4)
memory usage: 2.9 MB

In [87]:
raw_df.describe().T

,count,mean,std,min,25%,50%,75%,max
FRUITS_VEGGIES,15972.0,2.922677,1.442694,0.0,2.0,3.0,4.0,5.0
PLACES_VISITED,15972.0,5.232970,3.311912,0.0,2.0,5.0,8.0,10.0
CORE_CIRCLE,15972.0,5.508077,2.840334,0.0,3.0,5.0,8.0,10.0
SUPPORTING_OTHERS,15972.0,5.616454,3.242021,0.0,3.0,5.0,10.0,10.0
SOCIAL_NETWORK,15972.0,6.474267,3.086672,0.0,4.0,6.0,10.0,10.0
ACHIEVEMENT,15972.0,4.000751,2.755837,0.0,2.0,3.0,6.0,10.0
DONATION,15972.0,2.715314,1.851586,0.0,1.0,3.0,5.0,5.0
BMI_RANGE,15972.0,1.410656,0.491968,1.0,1.0,1.0,2.0,2.0
TODO_COMPLETED,15972.0,5.745993,2.624097,0.0,4.0,6.0,8.0,10.0
FLOW,15972.0,3.194778,2.357518,0.0,1.0,3.0,5.0,10.0
DAILY_STEPS,15972.0,5.703606,2.891013,1.0,3.0,5.0,8.0,10.0
LIVE_VISION,15972.0,3.752129,3.230987,0.0,1.0,3.0,5.0,10.0
SLEEP_HOURS,15972.0,7.042888,1.199044,1.0,6.0,7.0,8.0,10.0
LOST_VACATION,15972.0,2.898886,3.692180,0.0,0.0,0.0,5.0,10.0
DAILY_SHOUTING,15972.0,2.930879,2.676301,0.0,1.0,2.0,4.0,10.0
SUFFICIENT_INCOME,15972.0,1.728963,0.444509,1.0,1.0,2.0,2.0,2.0
PERSONAL_AWARDS,15972.0,5.711558,3.089630,0.0,3.0,5.0,9.0,10.0
TIME_FOR_PASSION,15972.0,3.326572,2.729293,0.0,1.0,3.0,5.0,10.0
WEEKLY_MEDITATION,15972.0,6.233346,3.016571,0.0,4.0,7.0,10.0,10.0
WORK_LIFE_BALANCE_SCORE,15972.0,666.751503,45.019868,480.0,636.0,667.7,698.5,820.2

**<h2>Phase 2 Objective</h2>**

The objective of this notebook is to evaluate the quality of the raw dataset and create a validated clean_df suitable for exploratory data analysis (EDA), while preserving the original raw_df.

This notebook will focus on identifying and correcting issues such as:

Missing values,<br>
Duplicate records,<br>
Incorrect data types,<br>
Invalid or inconsistent values,<br>
Structural inconsistencies

<h3> Expected Deliverables </h3>

By the end of this notebook, we should know:

Missing value counts<br>
Duplicate record counts<br>
Data type consistency<br>
Invalid categorical values<br>
Numeric value ranges<br>
Final cleaned dataset (clean_df)

In [88]:
clean_df = raw_df.copy()

In [89]:
missing_summary = pd.DataFrame({
    "Missing Count": clean_df.isnull().sum(),
    "Missing Percentage": (clean_df.isnull().sum() / len(clean_df) * 100).round(2)
})

missing_summary = missing_summary.sort_values(
    by="Missing Percentage",
    ascending=False
)

display(missing_summary)

                         Missing Count  Missing Percentage
Timestamp                            0                 0.0
FRUITS_VEGGIES                       0                 0.0
DAILY_STRESS                         0                 0.0
PLACES_VISITED                       0                 0.0
CORE_CIRCLE                          0                 0.0
SUPPORTING_OTHERS                    0                 0.0
SOCIAL_NETWORK                       0                 0.0
ACHIEVEMENT                          0                 0.0
DONATION                             0                 0.0
BMI_RANGE                            0                 0.0
TODO_COMPLETED                       0                 0.0
FLOW                                 0                 0.0
DAILY_STEPS                          0                 0.0
LIVE_VISION                          0                 0.0
SLEEP_HOURS                          0                 0.0
LOST_VACATION                        0                 0.0
DAILY_SHOUTING                       0                 0.0
SUFFICIENT_INCOME                    0                 0.0
PERSONAL_AWARDS                      0                 0.0
TIME_FOR_PASSION                     0                 0.0
WEEKLY_MEDITATION                    0                 0.0
AGE                                  0                 0.0
GENDER                               0                 0.0
WORK_LIFE_BALANCE_SCORE              0                 0.0

In [90]:
print(" Printing the unique values of every column :")
for col in clean_df.columns[1:]:
    print(f" The unique values in {col} are : {clean_df[col].unique()}")

 Printing the unique values of every column :
 The unique values in FRUITS_VEGGIES are : [3 2 5 4 1 0]
 The unique values in DAILY_STRESS are : <StringArray>
['2', '3', '1', '4', '5', '0', '01-01-2000']
Length: 7, dtype: str
 The unique values in PLACES_VISITED are : [ 2  4  3 10  5  6  7  0  8  1  9]
 The unique values in CORE_CIRCLE are : [ 5  3  4  9  6  7  8 10  2  1  0]
 The unique values in SUPPORTING_OTHERS are : [ 0  8  4 10  5  3  1  2  6  7  9]
 The unique values in SOCIAL_NETWORK are : [ 5 10  7  4  3  1  2  8  6  9  0]
 The unique values in ACHIEVEMENT are : [ 2  5  3  4  0  1  6 10  8  7  9]
 The unique values in DONATION are : [0 2 5 4 3 1]
 The unique values in BMI_RANGE are : [1 2]
 The unique values in TODO_COMPLETED are : [ 6  5  2  3  8 10  7  4  1  0  9]
 The unique values in FLOW are : [ 4  2  5  0  1  8  7  6  3 10  9]
 The unique values in DAILY_STEPS are : [ 5  4  7  8  1  3  6  2 10  9]
 The unique values in LIVE_VISION are : [ 0  5 10  4  2  1  6  3  8  9  7]
 The unique values in SLEEP_HOURS are : [ 7  8  5  6 10  9  4  3  2  1]
 The unique values in LOST_VACATION are : [ 5  2 10  7  0  3  1  4  8  6  9]
 The unique values in DAILY_SHOUTING are : [ 5  2  0  3  1  7  6  4 10  8  9]
 The unique values in SUFFICIENT_INCOME are : [1 2]
 The unique values in PERSONAL_AWARDS are : [ 4  3  5  8 10  1  2  7  6  0  9]
 The unique values in TIME_FOR_PASSION are : [ 0  2  8  1  3  6  5  4 10  9  7]
 The unique values in WEEKLY_MEDITATION are : [ 5  6  3  0 10  2  1  7  4  8  9]
 The unique values in AGE are : <StringArray>
['36 to 50', '51 or more', '21 to 35', 'Less than 20']
Length: 4, dtype: str
 The unique values in GENDER are : <StringArray>
['Female', 'Male']
Length: 2, dtype: str
 The unique values in WORK_LIFE_BALANCE_SCORE are : [609.5 655.6 631.6 ... 651.7 611.5 790.5]

In [91]:
# Count duplicate rows

duplicate_count = clean_df.duplicated().sum()

print(f"Total Duplicate Rows : {duplicate_count}")

Total Duplicate Rows : 482

In [92]:
if duplicate_count > 0:
    duplicate_rows = clean_df[clean_df.duplicated(keep=False)]
    display(duplicate_rows.sort_values(by=duplicate_rows.columns.tolist()))
else:
    print("No duplicate rows found.")

,Timestamp,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,TODO_COMPLETED,FLOW,DAILY_STEPS,LIVE_VISION,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,AGE,GENDER,WORK_LIFE_BALANCE_SCORE
5342,01-01-2017,0,4,6,1,2,2,0,2,2,3,1,2,0,7,10,5,1,3,2,5,21 to 35,Female,554.5
5343,01-01-2017,0,4,6,1,2,2,0,2,2,3,1,2,0,7,10,5,1,3,2,5,21 to 35,Female,554.5
2030,01-03-2016,5,0,10,4,6,5,6,5,2,8,2,10,0,6,0,2,1,8,2,10,51 or more,Female,691.9
2031,01-03-2016,5,0,10,4,6,5,6,5,2,8,2,10,0,6,0,2,1,8,2,10,51 or more,Female,691.9
5362,01-03-2017,0,4,3,0,3,2,0,0,1,1,1,2,1,8,10,0,2,0,6,10,21 to 35,Male,595.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,9/29/15,3,3,5,8,4,10,3,0,1,3,4,6,0,5,0,0,1,4,1,7,21 to 35,Female,648.4
973,9/30/15,2,4,4,9,2,9,5,0,2,8,3,1,1,6,10,8,1,4,3,2,36 to 50,Female,588.1
976,9/30/15,2,4,4,9,2,9,5,0,2,8,3,1,1,6,10,8,1,4,3,2,36 to 50,Female,588.1
4576,9/30/16,3,5,4,6,5,10,5,5,1,7,3,6,10,6,10,3,1,10,4,10,21 to 35,Female,680.9
4577,9/30/16,3,5,4,6,5,10,5,5,1,7,3,6,10,6,10,3,1,10,4,10,21 to 35,Female,680.9

**As i can see here most of the duplicate values have a weird pattern that is they are appearing just after another also most of them are appearing on the same date which indicates that there is a very high probability that those values are the real duplicate values and hence i am dropping those values**

In [93]:
from encodings.punycode import T

clean_df.drop_duplicates(inplace=True)

In [94]:
clean_df.head()

,Timestamp,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,TODO_COMPLETED,FLOW,DAILY_STEPS,LIVE_VISION,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,AGE,GENDER,WORK_LIFE_BALANCE_SCORE
0,07-07-2015,3,2,2,5,0,5,2,0,1,6,4,5,0,7,5,5,1,4,0,5,36 to 50,Female,609.5
1,07-07-2015,2,3,4,3,8,10,5,2,2,5,2,5,5,8,2,2,2,3,2,6,36 to 50,Female,655.6
2,07-07-2015,2,3,3,4,4,10,3,2,2,2,2,4,5,8,10,2,2,4,8,3,36 to 50,Female,631.6
3,07-07-2015,3,3,10,3,10,7,2,5,2,3,5,5,0,5,7,5,1,5,2,0,51 or more,Female,622.7
4,07-07-2015,5,1,3,3,10,4,2,4,2,5,0,5,0,7,0,0,2,8,1,5,51 or more,Female,663.9

In [95]:
clean_df.drop(columns=["Timestamp"], inplace = True)
clean_df = clean_df[clean_df["DAILY_STRESS"] != '01-01-2000']
clean_df['AGE'] = clean_df['AGE'].map({ "Less than 20": 0, "21 to 35": 1, "36 to 50": 2, "51 or more": 3 })
clean_df = pd.get_dummies(clean_df, columns=['GENDER'], drop_first=True)
clean_df['DAILY_STRESS'] = clean_df['DAILY_STRESS'].astype("int64")

In [96]:
clean_df.to_csv('dataset\\clean_dataset.csv', index=False)